table AMZN
	lineageTag: 67643a70-6921-41b9-8707-3353645e7e46

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: bdc7f224-c8a2-4979-bbe5-52cde54a1b86
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 19271505-f8a9-4942-b313-87c012752ae8
			defaultHierarchy: LocalDateTable_012adc22-cb33-45ab-acaf-764b46326c45.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: f462485a-3326-4c19-92f2-fb3b8862b435
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: 2c5bab20-e9b7-4ab7-96ed-8f5962e16f9d
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 1a65b68f-ba5a-427e-a319-6b398ac6f86b
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: ccbcf204-61c4-46be-b55e-c367657034bf
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: ae115060-9f30-4583-984c-105c389dd1cc
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: 35862861-20b5-4208-ab72-f33d726663fd
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\afarkya\Documents\VSS-Repo\MyFirstRepository\AMZN.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

